### ISSUE TITLE
`git clone --recursive` to install packages

### ISSUE THREAD

**Issue by hauleth** [wa/wahoo#100]
I know that everything is migrating to Fin but I want to mark it here as Fin is still in progress (BTW why new name & project instead maintaining this one?).

**Comment by bucaran** [comment]
@hauleth I will keep maintaining Wahoo, perhaps until or after I release Fin and to help people migrate. 

> ...why new name & project instead...?

Implementation-wise, Fin is completely different from Wahoo. It's my best iteration so far in terms of "fish frameworks".

> `git clone --recursive` to install packages

As you know, packages exist in a different repo, so I am not sure how this could be done.

**Comment by hauleth** [comment]
Yes. I mean when you clone that remote repo you should use `git clone --recursive`. I found this when I created https://github.com/hauleth/pkg-rust that use external repository with completions.

**Comment by bucaran** [comment]
@hauleth Sure. Do you want to send me a PR with that?

**Comment by hauleth** [comment]
Here you are #103

**Comment by bucaran** [comment]
:+1: Thanks.
