### ISSUE TITLE
Event handler issue after the installation of the pyenv plugin

### ISSUE THREAD

**Issue by sdouche** [wa/wahoo#105]
Hi
on a fresh Wahoo install, I'm trying to install the pyenv plugin (pyenv v20151006):

```
Installing pyenv...
✔ pyenv succesfully installed.
/home/sdouche/.wahoo/pkg/pyenv/pyenv.fish (line 2): pyenv init - | psub
                                                    ^
in command substitution
	called on line 5 of file “/home/sdouche/.wahoo/pkg/pyenv/pyenv.fish”,

in function “init”,
	called on line 1 of file “/home/sdouche/.wahoo/init.fish”,
	with parameter list “/home/sdouche/.wahoo/pkg/pyenv”

in event handler: handler for generic event “init_pyenv”
```

**Comment by bucaran** [comment]
You may be running an older version of Wahoo. Can you check that your `init.fish` is the same as https://github.com/wa/wahoo/blob/master/init.fish?

**Comment by sdouche** [comment]
Hi @bucaran 
Sorry for the late reply. On another machine (a fresh Wahoo install too), it works. My bad. Now I've a issue with the pyenv but it's another story :).
