### ISSUE TITLE
Show description before installing theme / plugin

### ISSUE THREAD

**Issue by TeddyDD** [wa/wahoo#26]
It could be done via fetching README.md of plugin or theme

**Comment by bucaran** [comment]
Good idea. This can be done adding the description text to the package entry file under `db/[pkg/themes]` and shown when listing packages and using fish completions.

**Comment by gretel** [comment]
makes me think of a `JSON` lib for fish

**Comment by bucaran** [comment]
It would be slow.

→ github.com/bucaran/jon

**Comment by gretel** [comment]
thanks for pointing that out :bird: we'd need conversion to `JSON`, too. how about linking a issue of `jon` in regards to speed to `fish-shell`?

**Comment by bucaran** [comment]
Sure. Sounds good to me.

I will be integrating `getopts` into Wahoo's core lib as well, it's essential if you are writing utilities with complex set of flags.

**Comment by bucaran** [comment]
Could still happen, it's a nice little feature. In the meantime, we can always check the package GitHub repository to see what it is about.
