### ISSUE TITLE
'wa update' should update all packages

### ISSUE THREAD

**Issue by s0r00t** [wa/wahoo#38]
'wa update' should act like an update command from a package manager: updating Wahoo and its packages.

If possible, it could update fish, but that would require checking the OS and such.

(This idea was discussed on Gitter.)

**Comment by bucaran** [comment]
:+1: Absolutely

Maybe via a flag or this should be the default behavior?

> If possible, it could update fish, but that would require checking the OS and such.

Definitely only behind a flag

```
wa up --fish
// brew uninstall fish; brew install fish --HEAD 
```

**Comment by gretel** [comment]
bit less destructive would be
```
$ brew unlink fish; brew install fish --HEAD; brew link fish
```

**Comment by bucaran** [comment]
@gretel Nice.

`wa u` will never interfere with `fish`, but yes, I am currently working on supporting

> 'wa update' should update all packages

**Comment by gretel** [comment]
i feel it does interfere with `fish` because it may have actually been building it :relieved:

**Comment by bucaran** [comment]
@gretel Haha, well said. However, that is the boostrap.sh, `wa` does not interfere with fish.

**Comment by bucaran** [comment]
Closing in favor of #59
