### ISSUE TITLE
consider installing wahoo into ~/.local/share/wahoo by default instead of ~/.wahoo

### ISSUE THREAD

**Issue by jrobeson** [wa/wahoo#75]
Specifically, it'd be nice to use the XDG_DATA_HOME variable which defaults ~/.local/share/wahoo if not set.

**Comment by bucaran** [comment]
@jrobeson Thanks! A few questions:

+ Why?
+ Where is the documentation for `XDG_DATA_HOME`? 
+ How will it affect OSX users?

**Comment by faho** [comment]
>Why?

Usually the reason given is to keep $HOME clean. You might also notice that fish itself already uses $XDG_CONFIG_HOME (defaulting to ~/.config).

>Where is the documentation for XDG_DATA_HOME? 

That'd be the [basedir spec](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

The relevant parts are:

> There is a single base directory relative to which user-specific data files should be written. This directory is defined by the environment variable $XDG_DATA_HOME. 

and

> $XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.

**Comment by jrobeson** [comment]
Ah, i misassumed familiarity due to fish itself using $XDG_CONFIG_HOME . Sorry folks

**Comment by bucaran** [comment]
I didn't know `$XDG_CONFIG_HOME` would be a more sensible default. Sounds good. I'll patch this in the next release along with other small fixes as soon as I can.

@gretel Thoughts?

**Comment by jrobeson** [comment]
I might take this on

**Comment by bucaran** [comment]
Go for it :smile:

**Comment by bucaran** [comment]
4f51a43b820d00b649ea2cc982962f3b40010ccb
