### ISSUE TITLE
Supporting other package managers in bootstrap script

### ISSUE THREAD

**Issue by jrobeson** [wa/wahoo#76]
I'm not sure how this shoudl be done properly, but it'd be nice to support other package managers like pacman on Arrch, zypper on OpenSuse and dnf on Fedora 22 and above,

Currently Fedora 22 will print an ugly warning when attempting to use the yum command due to it disappearing in the next release or so.

So it seems like we'll need a way to detect distributions and versions to choose the appropriate package manager.

**Comment by jrobeson** [comment]
Is it possible that we could have instructions on how to manually setup wahoo in the meantime?

**Comment by faho** [comment]
For arch, if you want to install fish you could either install it via the repo (which is usually rather up-to-date) with `pacman -S fish`, or you could build your own git package via [fish-shell-git](https://aur.archlinux.org/packages/fish-shell-git/) in the AUR (don't mind the version there, it auto-updates to the latest git code). I think that should be encouraged over manual `make; make install` because it's easier to remove and easier to do because dependencies are already cared for.

**Comment by bucaran** [comment]
@jrobeson Perhaps we should simply have `bootstrap.sh` install Wahoo and require users to install fish themselves.

**Comment by bucaran** [comment]
@jrobeson What is your OS?

**Comment by bucaran** [comment]
The script should work if you already have fish installed.

```sh
  if ! util_env_can "fish"; then
    util_log INFO  "Installing 'fish'"
    if lib_fish_install; then
      util_log INFO "Setting 'fish' as your default shell"
      lib_fish_set_as_default_shell
    fi
  fi

  if lib_wahoo_install; then
    util_log_default_success "Wahoo"
    util_display_success_msg

    cd $HOME

    if [ -z ${CI+_} ]; then
      util_env_swap_process "fish"
    fi
  else
    util_log ERROR "Alas, Wahoo failed to install correctly"
    util_log INFO "Please complain here → git.io/wahoo-issues"
    exit 1
  fi
```

**Comment by jrobeson** [comment]
my problem is the lack of support for DNF on Fedora and thus spewing an ugly warning when it uses the yum fallback (which will disappear in an upcoming Fedora release). I just brought up the other distros, so it would work properly for other systems that aren't don't use apt or yum.

**Comment by bucaran** [comment]
@jrobeson I see. Were you able to install Wahoo? 

I am no Fedora expert, so I would appreciate a PR addressing this issue.

**Comment by jrobeson** [comment]
I can install it now I'm sure, but that won't be the case in the next few months.

**Comment by jrobeson** [comment]
I'd like to split out the logic in which we find the package manager, instead of cluttering the bootstrap script with

if x
else if y
else if z
else if d

etc...

**Comment by bucaran** [comment]
@jrobeson What's the status on this issue? Are you having any problems?

**Comment by jrobeson** [comment]
it's not priority compared to the XDG changes.

**Comment by bucaran** [comment]
I will be pushing Wahoo 1.0.0 shortly. Now git and Fish are system requirements.
