### ISSUE TITLE
renaming $BASE and $CUSTOM in bootstrap.sh

### ISSUE THREAD

**Issue by jrobeson** [wa/wahoo#87]
I'm having a little trouble coming up with a good name for the variable. My current (working) change just uses WAHOO_DATA_HOME instead of $BASE, but that was just because I couldn't think think of anything better.

Can you explain what $CUSTOM is actually for? What does it serve that the regular fish directory already doesn't ?

**Comment by bucaran** [comment]
To customize the `.dotfiles` directory completly. I use `~/.rc`, but using this you could set `CUSTOM=~/dev/.myconfig` or whatever right/

**Comment by jrobeson** [comment]
i know what I can set it to, but I don't know what the purpose is. why would I use it over just putting stuff in the fish directories (~/.config/fish, ~/.local/share/fish)

**Comment by bucaran** [comment]
To customize your dotfiles directory. For example, in OMF it defaults to `~/.dotfiles`, or whatever you set the `$fish_custom` variable to. I think `~/.dotfiles` was a sensible default, but I prefer `~/.rc`, so when I install Wahoo in a new computer (for example when I join a new company / project and they give me a new machine) I always set `CUSTOM=~/.rc` when doing `curl -L git.io/wa | sh`

**Comment by jrobeson** [comment]
but what do you put in there?

**Comment by bucaran** [comment]
I put [my dotfiles](https://github.com/bucaran/rc) in there and use a script in the same repo that lets me synchronize the stuff with GitHub every now and then. 

Also relevant: https://dotfiles.github.io/

**Comment by jrobeson** [comment]
I still don't get why this is part of wahoo then.

**Comment by bucaran** [comment]
We use it [here](https://github.com/wa/wahoo/blob/master/init.fish#L33)

If you are not using this, you are missing out on a powerful feature. Here is one of example where having dotfiles is useful:

+ You can have a `pkg` or `themes` directory and store local packages (e.g., still work in progress stuff, private, etc)
+ Any package in there with the same name as an existing one will be preferred over the official one, letting override default stuff.
+ `$WAHOO_CUSTOM/functions` is autoloaded. So, you don't need to mess with the `config.fish` file (in fact you should not).

**Comment by jrobeson** [comment]
yeah.. it definitely should be in the README :)  I read the code, but i still didn't really grasp it until now.

So what should we call the environment variables for these in bootstrap.sh? atm the name doesn't really reflect what they do, but at the same time it shouldn't be too long either. As mentioned before, my current change for BASE is to WAHOO_DATA_HOME, but that's just because I couldn't think of anything better.

**Comment by bucaran** [comment]
Well, can you make a single PR with all your changes so that I can go over it?

**Comment by jrobeson** [comment]
fixed in #91
